version: 0.0
os: linu
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: beforeInstall.sh
      timeout: 100
  ApplicationStart:
    - location: applicationStart.sh
      timeout: 100
